alias a="alias "
alias b="pbcopy"
alias bd=". bd -si"
alias bs="brew search --desc "
alias bin="brew install"
alias c="cat"
alias cl="clear"
#alias d=	当前工作目录
alias e="echo"
alias f="find"
alias fname="find . -name '*' | grep $* "
# 搜索文件内容
alias fs='_gfile(){ grep $2 $1 }; _gfile $1 $2'

# alias g=	git
# alias h= 	历史记录
alias hc="fc -l -n 1 | grep  $*"
alias i=""
# alias j=  autojump
alias k=""
alias l="ls"
alias log="adb logcat -v threadtime| grep --color $*"
alias logp='_logp(){ echo 111}; _logp() $1'
alias lr="ls -a | grep $*"
alias m="move"
alias n="touch"
alias o="open"
alias of="open `pwd`"
unalias p
alias p= pwd
alias py="python2.7"
alias q=""
alias r="grep "
alias s="subl"
# alias t= tail
alias u="unalias"
alias v="vim"
alias w="where"
alias x="xargs"
alias y="where"
# alias z=列举最常用的工作目录
